
GET http://localhost/api/users

###

POST http://localhost/api/users
Content-Type: application/json

{
    "userID": "Manfred",
    "firstName": "Manfred",
    "lastName": "Mustermann",
    "password": "asdf"
}
###
POST http://localhost/api/publicUsers
Content-Type: application/json

{
    "userID": "Manfred2",
    "firstName": "Manfred",
    "lastName": "Mustermann",
    "password": "asdf"
}